### PR TITLE
Add jadelint object to Stream

### PR DESCRIPTION
**Pull request by popcorn245**
Add a jadelint object to file in stream that has errors and warnings so they may be used and counted.

### CODE REVIEW

**Comment by rrdelaney** [comment]
Hi! I'm the author of jadelint.

This looks good :smile: do you have a specific use case for this?

**Comment by patwork** [comment]
Can you show an example of gulpfile which is using this change?

**Comment by popcorn245** [comment]
``` js
gulp.task('html-lint', function(){
    var errorCount = 0;
    return gulp.src(htmlWatch)
        .pipe(plumber({
            errorHandler: function(error) {
                browserSync.notify(error.message, errorTimeout);
                this.emit('end');
            }
        }))
        .pipe(jadelint())
        .pipe(intercept(function(file) {
            if(file.jadelint.errors.length > 0){
                errorCount = errorCount + file.jadelint.errors.length;
            }
        }))
        .on('end', function(){
            if(errorCount === 0 && global.isWatching){
                runSequence('html-compile', 'sync-reload');
            }
        });
});
```

**Comment by patwork** [comment]
Will not work with jadelint v0.3

**Pull request closed without merging**
